from .dto import MaintenanceRecordDTO, MaintenanceScheduleDTO
from .http import (
    MaintenanceRecordCreateRequest,
    MaintenanceRecordResponse,
    MaintenanceRecordUpdateRequest,
    MaintenanceScheduleCompleteRequest,
    MaintenanceScheduleCreateRequest,
    MaintenanceScheduleResponse,
    MaintenanceScheduleUpdateRequest,
)
from .inputs import (
    MaintenanceRecordCreateInput,
    MaintenanceRecordDeleteInput,
    MaintenanceRecordGetInput,
    MaintenanceRecordListInput,
    MaintenanceRecordUpdateInput,
    MaintenanceScheduleCompleteInput,
    MaintenanceScheduleCreateInput,
    MaintenanceScheduleDeleteInput,
    MaintenanceScheduleDueByDateInput,
    MaintenanceScheduleDueByMileageInput,
    MaintenanceScheduleGetInput,
    MaintenanceScheduleListInput,
    MaintenanceScheduleUpdateInput,
)

__all__ = [
    "MaintenanceRecordCreateInput",
    "MaintenanceRecordCreateRequest",
    "MaintenanceRecordDTO",
    "MaintenanceRecordDeleteInput",
    "MaintenanceRecordGetInput",
    "MaintenanceRecordListInput",
    "MaintenanceRecordResponse",
    "MaintenanceRecordUpdateInput",
    "MaintenanceRecordUpdateRequest",
    "MaintenanceScheduleCompleteInput",
    "MaintenanceScheduleCompleteRequest",
    "MaintenanceScheduleCreateInput",
    "MaintenanceScheduleCreateRequest",
    "MaintenanceScheduleDTO",
    "MaintenanceScheduleDeleteInput",
    "MaintenanceScheduleDueByDateInput",
    "MaintenanceScheduleDueByMileageInput",
    "MaintenanceScheduleGetInput",
    "MaintenanceScheduleListInput",
    "MaintenanceScheduleResponse",
    "MaintenanceScheduleUpdateInput",
    "MaintenanceScheduleUpdateRequest",
]
