"""initial migration

Revision ID: 001
Revises: 
Create Date: 2026-04-29 10:44:18.374078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('cars',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('license_plate', sa.String(length=20), nullable=False),
    sa.Column('vin', sa.String(length=32), nullable=True),
    sa.Column('drive_type', sa.Enum('fwd', 'rwd', 'awd', 'four_wd', name='drive_type'), nullable=False),
    sa.Column('fuel_type', sa.Enum('petrol', 'diesel', 'hybrid', 'electric', 'gas', name='fuel_type'), nullable=False),
    sa.Column('transmission', sa.Enum('manual', 'automatic', 'robot', 'variator', name='transmission'), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('available', 'rented', 'in_repair', name='car_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cars_license_plate'), 'cars', ['license_plate'], unique=False)
    op.create_index(op.f('ix_cars_organization_id'), 'cars', ['organization_id'], unique=False)
    op.create_table('organization_members',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('owner', name='organization_role'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_organization_members_org_user')
    )
    op.create_index(op.f('ix_organization_members_organization_id'), 'organization_members', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_members_user_id'), 'organization_members', ['user_id'], unique=False)
    op.create_table('bookings',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('car_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('renter_name', sa.String(length=255), nullable=False),
    sa.Column('renter_phone', sa.String(length=32), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pickup_mileage', sa.Integer(), nullable=True),
    sa.Column('return_mileage', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('planned', 'active', 'completed', 'cancelled', name='booking_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_car_id'), 'bookings', ['car_id'], unique=False)
    op.create_index(op.f('ix_bookings_organization_id'), 'bookings', ['organization_id'], unique=False)
    op.create_table('car_photos',
    sa.Column('car_id', sa.Uuid(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_photos_car_id'), 'car_photos', ['car_id'], unique=False)
    op.create_table('car_pricing_tiers',
    sa.Column('car_id', sa.Uuid(), nullable=False),
    sa.Column('min_days', sa.Integer(), nullable=False),
    sa.Column('daily_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('car_id', 'min_days', name='uq_car_pricing_tiers_car_min_days')
    )
    op.create_index(op.f('ix_car_pricing_tiers_car_id'), 'car_pricing_tiers', ['car_id'], unique=False)
    op.create_table('insurance_payments',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('car_id', sa.Uuid(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_payments_car_id'), 'insurance_payments', ['car_id'], unique=False)
    op.create_index(op.f('ix_insurance_payments_organization_id'), 'insurance_payments', ['organization_id'], unique=False)
    op.create_table('maintenance_records',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('car_id', sa.Uuid(), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('service_type', sa.Enum('oil_change', 'tires', 'brakes', 'inspection', 'repair', 'other', name='service_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('mileage_at_service', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_records_car_id'), 'maintenance_records', ['car_id'], unique=False)
    op.create_index(op.f('ix_maintenance_records_organization_id'), 'maintenance_records', ['organization_id'], unique=False)
    op.create_table('maintenance_schedules',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('car_id', sa.Uuid(), nullable=False),
    sa.Column('service_type', sa.Enum('oil_change', 'tires', 'brakes', 'inspection', 'repair', 'other', name='service_type'), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('scheduled_mileage', sa.Integer(), nullable=True),
    sa.Column('interval_km', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('maintenance_record_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint('scheduled_date IS NOT NULL OR scheduled_mileage IS NOT NULL', name='ck_maintenance_schedules_date_or_mileage'),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['maintenance_record_id'], ['maintenance_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_schedules_car_id'), 'maintenance_schedules', ['car_id'], unique=False)
    op.create_index(op.f('ix_maintenance_schedules_organization_id'), 'maintenance_schedules', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_schedules_organization_id'), table_name='maintenance_schedules')
    op.drop_index(op.f('ix_maintenance_schedules_car_id'), table_name='maintenance_schedules')
    op.drop_table('maintenance_schedules')
    op.drop_index(op.f('ix_maintenance_records_organization_id'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_car_id'), table_name='maintenance_records')
    op.drop_table('maintenance_records')
    op.drop_index(op.f('ix_insurance_payments_organization_id'), table_name='insurance_payments')
    op.drop_index(op.f('ix_insurance_payments_car_id'), table_name='insurance_payments')
    op.drop_table('insurance_payments')
    op.drop_index(op.f('ix_car_pricing_tiers_car_id'), table_name='car_pricing_tiers')
    op.drop_table('car_pricing_tiers')
    op.drop_index(op.f('ix_car_photos_car_id'), table_name='car_photos')
    op.drop_table('car_photos')
    op.drop_index(op.f('ix_bookings_organization_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_car_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_organization_members_user_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_organization_id'), table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_index(op.f('ix_cars_organization_id'), table_name='cars')
    op.drop_index(op.f('ix_cars_license_plate'), table_name='cars')
    op.drop_table('cars')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
